### ISSUE TITLE
給大神的感謝跟建議

### ISSUE THREAD

**Issue by LiChenJoe** [onlinemad/5000-lottery#11]
Hello 大神～
我是JS菜菜雞～
目前雖然JS功能都還沒學完，但一開始單純想製作些什麼，
所以目前用半人工的方式繼續製作五倍券查詢。
首先想謝謝你的版本，讓我發現多JS還有很多厲害功能的要學，增加我很多動力！
我用你的速查一邊在對照我自己的正確性，
有抓到我有一兩個錯誤(再次感謝你的工具QQ)！
Anyway，我發現大神你的宿查，目前看到771的結果似乎有誤，缺了第三週的地生券。
再提供給大神參考～

再次謝謝你的工具，給我很多啟發！

**Comment by onlinemad** [comment]
謝謝你的 issue ，我抄錯號碼了 😅
已經修正了 👍
