### ISSUE TITLE
請加入清空 input 值

### ISSUE THREAD

**Issue by hokou** [onlinemad/5000-lottery#3]
請協助修改讓輸入值可以不要儲存或是從本機刪除
因家中長輩想分享卻發現會儲存而怕個資問題

謝謝

**Comment by MrOrz** [comment]
But it is a feature, not a bug
https://github.com/onlinemad/5000-lottery/blob/master/README.md?plain=1#L10

作者之所以把號碼存 localStorage，應該是方便大家在未來幾週新開獎的時候，回來直接送出看新結果吧

**Comment by hokou** [comment]
對，因為儲存的內容算是身分證(雖然只是部分)，屬於較敏感資訊
因此再點進去網址卻發現剛剛的內容還是存在，對一般人來說會怕怕的
才會建議刪除或不儲存，加個按鈕跟備註說明也可以
