### ISSUE TITLE
強化 CSS & 使用者體驗

### ISSUE THREAD

**Issue by LuckyPigeon** [onlinemad/5000-lottery#6]
我本來也要寫同樣的東西，但看來被你搶先了。使用過你的網站後，有些小建議。不介意的話，我可以改完開個分支讓你 Review 一下嗎？
下方是我畫的 Wireframe，主要強化以下幾點：
  * 以 CSS 強化使用者對網站的印象
  * 新增表格查詢多個身分證以及每週種了哪些號碼
  * 用 Logo 和按鈕取代一些科技術語
  * 新增超連結
![image](https://user-images.githubusercontent.com/32315294/137522889-0881793b-f9a4-450e-801d-cfa0cc565412.png)

**Comment by sexyoung** [comment]
我也有寫一個耶，歡迎來我這邊發 PR XD
https://sexyoung.github.io/vhpi.5000/

@LuckyPigeon

**Comment by onlinemad** [comment]
@LuckyPigeon 謝謝你的建議

我看了你的 pull ，大概就是

1. 用 table 排版在手機檢視會超過畫面
2. 原始設計是希望可以輸入多筆身分證，這樣就可以方便全家查
3. 雖然檢查身分證字號的立意很好，但是這樣就沒辦法只輸入三碼查詢
4. 原始設計會把身分證字號存在 localStorage 這樣下次再進來就可以載入原本輸入的身分證資料，同時 #3 也加了清除功能，所以應該是可以保留暫存的功能

謝謝你的 pull 目前就沒有要 merge 這個 pull 了
